// Datasets de referencia exclusivos de Costa Rica (country_code = CR, currency = CRC).
// Compartidos entre el seed de PostgreSQL y el modo de demostración sin base de datos.

export const geografia: { nombre: string; cantones: string[] }[] = [
  { nombre: "San José", cantones: ["San José", "Escazú", "Desamparados", "Puriscal", "Tarrazú", "Aserrí", "Mora", "Goicoechea", "Santa Ana", "Alajuelita", "Vázquez de Coronado", "Acosta", "Tibás", "Moravia", "Montes de Oca", "Turrubares", "Dota", "Curridabat", "Pérez Zeledón", "León Cortés Castro"] },
  { nombre: "Alajuela", cantones: ["Alajuela", "San Ramón", "Grecia", "San Mateo", "Atenas", "Naranjo", "Palmares", "Poás", "Orotina", "San Carlos", "Zarcero", "Sarchí", "Upala", "Los Chiles", "Guatuso", "Río Cuarto"] },
  { nombre: "Cartago", cantones: ["Cartago", "Paraíso", "La Unión", "Jiménez", "Turrialba", "Alvarado", "Oreamuno", "El Guarco"] },
  { nombre: "Heredia", cantones: ["Heredia", "Barva", "Santo Domingo", "Santa Bárbara", "San Rafael", "San Isidro", "Belén", "Flores", "San Pablo", "Sarapiquí"] },
  { nombre: "Guanacaste", cantones: ["Liberia", "Nicoya", "Santa Cruz", "Bagaces", "Carrillo", "Cañas", "Abangares", "Tilarán", "Nandayure", "La Cruz", "Hojancha"] },
  { nombre: "Puntarenas", cantones: ["Puntarenas", "Esparza", "Buenos Aires", "Montes de Oro", "Osa", "Quepos", "Golfito", "Coto Brus", "Parrita", "Corredores", "Garabito", "Monteverde", "Puerto Jiménez"] },
  { nombre: "Limón", cantones: ["Limón", "Pococí", "Siquirres", "Talamanca", "Matina", "Guácimo"] },
];

export type StoreSeed = {
  nombre: string;
  slug: string;
  tipo: string;
  sitio: string | null;
  supermercado: boolean;
  logo: string;
  sucursales: { nombre: string; provincia: string; canton: string }[];
};

const tiendasCatalogo: StoreSeed[] = [
  {
    nombre: "Walmart Costa Rica",
    slug: "walmart-costa-rica",
    tipo: "SUPERMARKET",
    sitio: "https://www.walmart.co.cr",
    supermercado: true,
    logo: "/img/supermercados/originales/walmart-official.png",
    sucursales: [
      { nombre: "Walmart Curridabat", provincia: "San José", canton: "Curridabat" },
      { nombre: "Walmart Escazú", provincia: "San José", canton: "Escazú" },
      { nombre: "Walmart San Sebastián", provincia: "San José", canton: "San José" },
      { nombre: "Walmart Alajuela", provincia: "Alajuela", canton: "Alajuela" },
      { nombre: "Walmart Heredia", provincia: "Heredia", canton: "Heredia" },
      { nombre: "Walmart Cartago", provincia: "Cartago", canton: "Cartago" },
      { nombre: "Walmart Liberia", provincia: "Guanacaste", canton: "Liberia" },
      { nombre: "Walmart Puntarenas", provincia: "Puntarenas", canton: "Puntarenas" },
    ],
  },
  {
    nombre: "Automercado",
    slug: "automercado",
    tipo: "SUPERMARKET",
    sitio: "https://www.automercado.cr",
    supermercado: true,
    logo: "/img/supermercados/originales/automercado-display.png",
    sucursales: [
      { nombre: "Automercado San Rafael", provincia: "San José", canton: "Escazú" },
      { nombre: "Automercado Las Palmas", provincia: "San José", canton: "Santa Ana" },
      { nombre: "Automercado Multiplaza Curridabat", provincia: "San José", canton: "Curridabat" },
      { nombre: "Automercado Los Yoses", provincia: "San José", canton: "Montes de Oca" },
      { nombre: "Automercado Alajuela", provincia: "Alajuela", canton: "Alajuela" },
      { nombre: "Automercado Heredia", provincia: "Heredia", canton: "Heredia" },
      { nombre: "Automercado Playas del Coco", provincia: "Guanacaste", canton: "Carrillo" },
      { nombre: "Automercado Tamarindo", provincia: "Guanacaste", canton: "Santa Cruz" },
      { nombre: "Automercado Herradura", provincia: "Puntarenas", canton: "Garabito" },
    ],
  },
  {
    nombre: "MasxMenos",
    slug: "masxmenos",
    tipo: "SUPERMARKET",
    sitio: "https://www.masxmenos.cr",
    supermercado: true,
    logo: "/img/supermercados/originales/masxmenos-display.png",
    sucursales: [
      { nombre: "MasxMenos Paseo Colón", provincia: "San José", canton: "San José" },
      { nombre: "MasxMenos Sabana", provincia: "San José", canton: "San José" },
      { nombre: "MasxMenos San Pedro", provincia: "San José", canton: "Montes de Oca" },
      { nombre: "MasxMenos Alajuela", provincia: "Alajuela", canton: "Alajuela" },
      { nombre: "MasxMenos Heredia", provincia: "Heredia", canton: "Heredia" },
      { nombre: "MasxMenos Cartago", provincia: "Cartago", canton: "Cartago" },
      { nombre: "MasxMenos Jacó", provincia: "Puntarenas", canton: "Garabito" },
      { nombre: "MasxMenos Limón", provincia: "Limón", canton: "Limón" },
    ],
  },
  {
    nombre: "Palí",
    slug: "pali",
    tipo: "SUPERMARKET",
    sitio: "https://www.walmart.co.cr",
    supermercado: true,
    logo: "/img/supermercados/originales/pali-display.png",
    sucursales: [
      { nombre: "Palí Desamparados", provincia: "San José", canton: "Desamparados" },
      { nombre: "Palí Alajuela Centro", provincia: "Alajuela", canton: "Alajuela" },
      { nombre: "Palí San Ramón", provincia: "Alajuela", canton: "San Ramón" },
      { nombre: "Palí Cartago Centro", provincia: "Cartago", canton: "Cartago" },
      { nombre: "Palí Turrialba", provincia: "Cartago", canton: "Turrialba" },
      { nombre: "Palí Heredia Centro", provincia: "Heredia", canton: "Heredia" },
      { nombre: "Palí Nicoya", provincia: "Guanacaste", canton: "Nicoya" },
      { nombre: "Palí Santa Cruz", provincia: "Guanacaste", canton: "Santa Cruz" },
      { nombre: "Palí Puntarenas Centro", provincia: "Puntarenas", canton: "Puntarenas" },
      { nombre: "Palí Esparza", provincia: "Puntarenas", canton: "Esparza" },
      { nombre: "Palí Limón Centro", provincia: "Limón", canton: "Limón" },
      { nombre: "Palí Guápiles", provincia: "Limón", canton: "Pococí" },
      { nombre: "Palí Siquirres", provincia: "Limón", canton: "Siquirres" },
    ],
  },
  {
    nombre: "MaxiPalí",
    slug: "maxipali",
    tipo: "SUPERMARKET",
    sitio: "https://www.masxmenos.cr",
    supermercado: true,
    logo: "/img/supermercados/originales/maxipali-display.png",
    sucursales: [
      { nombre: "MaxiPalí Santa Ana", provincia: "San José", canton: "Santa Ana" },
      { nombre: "MaxiPalí Alajuelita", provincia: "San José", canton: "Alajuelita" },
      { nombre: "MaxiPalí Heredia", provincia: "Heredia", canton: "Heredia" },
      { nombre: "MaxiPalí El Guarco", provincia: "Cartago", canton: "El Guarco" },
      { nombre: "MaxiPalí Liberia", provincia: "Guanacaste", canton: "Liberia" },
      { nombre: "MaxiPalí Quepos", provincia: "Puntarenas", canton: "Quepos" },
      { nombre: "MaxiPalí Guápiles", provincia: "Limón", canton: "Pococí" },
    ],
  },
  {
    nombre: "PriceSmart Costa Rica",
    slug: "pricesmart-costa-rica",
    tipo: "CLUB",
    sitio: "https://www.pricesmart.com/site/cr/es",
    supermercado: true,
    logo: "/img/supermercados/originales/pricesmart-display.png",
    sucursales: [
      { nombre: "PriceSmart Curridabat", provincia: "San José", canton: "Curridabat" },
      { nombre: "PriceSmart Escazú", provincia: "San José", canton: "Escazú" },
      { nombre: "PriceSmart Zapote", provincia: "San José", canton: "San José" },
      { nombre: "PriceSmart Alajuela", provincia: "Alajuela", canton: "Alajuela" },
      { nombre: "PriceSmart Heredia", provincia: "Heredia", canton: "Heredia" },
      { nombre: "PriceSmart Tres Ríos", provincia: "Cartago", canton: "La Unión" },
      { nombre: "PriceSmart Liberia", provincia: "Guanacaste", canton: "Liberia" },
    ],
  },
  {
    nombre: "Megasuper",
    slug: "megasuper",
    tipo: "SUPERMARKET",
    sitio: "https://www.megasuper.com",
    supermercado: true,
    logo: "/img/supermercados/originales/megasuper-display.png",
    sucursales: [
      { nombre: "Megasuper Barrio La California", provincia: "San José", canton: "San José" },
      { nombre: "Megasuper Tibás", provincia: "San José", canton: "Tibás" },
      { nombre: "Megasuper Rohrmoser", provincia: "San José", canton: "San José" },
      { nombre: "Megasuper Alajuela", provincia: "Alajuela", canton: "Alajuela" },
      { nombre: "Megasuper Cartago", provincia: "Cartago", canton: "Cartago" },
      { nombre: "Megasuper Puntarenas", provincia: "Puntarenas", canton: "Puntarenas" },
    ],
  },
  {
    nombre: "Súper Servicentro",
    slug: "super-servicentro",
    tipo: "COMMERCE",
    sitio: null,
    supermercado: true,
    logo: "/img/supermercados/super-servicentro.svg",
    sucursales: [
      { nombre: "Súper Servicentro San José", provincia: "San José", canton: "San José" }
    ],
  },
  {
    nombre: "Peri",
    slug: "peri",
    tipo: "SUPERMARKET",
    sitio: "https://gessa.cr/marcas/peri",
    supermercado: true,
    logo: "/img/supermercados/peri.svg",
    sucursales: [{ nombre: "Peri San Pedro", provincia: "San José", canton: "Montes de Oca" }],
  },
  {
    nombre: "Super Compro",
    slug: "super-compro",
    tipo: "SUPERMARKET",
    sitio: "https://gessa.cr/marcas/super-compro",
    supermercado: true,
    logo: "/img/supermercados/super-compro.svg",
    sucursales: [{ nombre: "Super Compro Liberia", provincia: "Guanacaste", canton: "Liberia" }],
  },
  {
    nombre: "Saretto",
    slug: "saretto",
    tipo: "SUPERMARKET",
    sitio: "https://gessa.cr/marcas/saretto",
    supermercado: true,
    logo: "/img/supermercados/saretto.svg",
    sucursales: [{ nombre: "Saretto Escazú", provincia: "San José", canton: "Escazú" }],
  },
  {
    nombre: "Súper Víquez",
    slug: "super-viquez",
    tipo: "SUPERMARKET",
    sitio: "https://gessa.cr/marcas/super-viquez",
    supermercado: true,
    logo: "/img/supermercados/super-viquez.svg",
    sucursales: [{ nombre: "Súper Víquez Heredia", provincia: "Heredia", canton: "Heredia" }],
  },
  {
    nombre: "Vindi",
    slug: "vindi",
    tipo: "CONVENIENCE",
    sitio: "https://www.automercado.cr",
    supermercado: true,
    logo: "/img/supermercados/vindi.svg",
    sucursales: [{ nombre: "Vindi Escazú", provincia: "San José", canton: "Escazú" }],
  },
  {
    nombre: "Fresh Market",
    slug: "fresh-market",
    tipo: "CONVENIENCE",
    sitio: "https://www.automercado.cr",
    supermercado: true,
    logo: "/img/supermercados/fresh-market.svg",
    sucursales: [{ nombre: "Fresh Market Santa Ana", provincia: "San José", canton: "Santa Ana" }],
  },
  {
    nombre: "AMPM",
    slug: "ampm",
    tipo: "CONVENIENCE",
    sitio: "https://www.ampm.cr",
    supermercado: true,
    logo: "/img/supermercados/ampm.svg",
    sucursales: [{ nombre: "AMPM San José", provincia: "San José", canton: "San José" }],
  },
  {
    nombre: "Delimart",
    slug: "delimart",
    tipo: "CONVENIENCE",
    sitio: "https://gessa.cr/marcas/delimart",
    supermercado: true,
    logo: "/img/supermercados/delimart.svg",
    sucursales: [{ nombre: "Delimart San José", provincia: "San José", canton: "San José" }],
  },
  {
    nombre: "Mayca",
    slug: "mayca",
    tipo: "WHOLESALE",
    sitio: "https://www.mayca.com",
    supermercado: true,
    logo: "/img/supermercados/mayca.svg",
    sucursales: [{ nombre: "Mayca Heredia", provincia: "Heredia", canton: "Heredia" }],
  },
  {
    nombre: "Pequeño Mundo",
    slug: "pequeno-mundo",
    tipo: "RETAIL",
    sitio: "https://www.pequenomundo.com",
    supermercado: true,
    logo: "/img/supermercados/pequeno-mundo.svg",
    sucursales: [{ nombre: "Pequeño Mundo San José", provincia: "San José", canton: "San José" }],
  },
  {
    nombre: "Maxiconsumo",
    slug: "maxiconsumo",
    tipo: "WHOLESALE",
    sitio: "https://gessa.cr",
    supermercado: true,
    logo: "/img/supermercados/maxiconsumo.svg",
    sucursales: [{ nombre: "Maxiconsumo Alajuela", provincia: "Alajuela", canton: "Alajuela" }],
  },
  {
    nombre: "Super Fácil",
    slug: "super-facil",
    tipo: "SUPERMARKET",
    sitio: "https://gessa.cr",
    supermercado: true,
    logo: "/img/supermercados/super-facil.svg",
    sucursales: [{ nombre: "Super Fácil San José", provincia: "San José", canton: "San José" }],
  },
];

// Solo exponemos cadenas con productos y precios disponibles en el catálogo actual.
export const tiendas: StoreSeed[] = tiendasCatalogo.slice(0, 7);

export type CategorySeed = { nombre: string; grupo: string; subcategorias: string[] };
export const categorias: CategorySeed[] = [
  { nombre: "Arroz y Granos", grupo: "Alimentación", subcategorias: ["Arroz blanco", "Arroz integral", "Frijoles negros", "Frijoles rojos", "Lentejas", "Garbanzos"] },
  { nombre: "Lácteos y Huevos", grupo: "Alimentación", subcategorias: ["Leche", "Queso", "Huevos", "Yogur", "Mantequilla"] },
  { nombre: "Carnes y Pollo", grupo: "Alimentación", subcategorias: ["Pollo entero", "Pechuga de pollo", "Res", "Cerdo", "Pescado"] },
  { nombre: "Frutas y Verduras", grupo: "Alimentación", subcategorias: ["Frutas frescas", "Verduras frescas", "Tubérculos"] },
  { nombre: "Aceites y Grasas", grupo: "Alimentación", subcategorias: ["Aceite de girasol", "Aceite vegetal", "Aceite de oliva", "Manteca"] },
  { nombre: "Pastas y Harinas", grupo: "Alimentación", subcategorias: ["Spaghetti", "Macarrones", "Harina de trigo", "Harina de maíz"] },
  { nombre: "Café y Bebidas", grupo: "Alimentación", subcategorias: ["Café molido", "Café soluble", "Té", "Jugos", "Gaseosas"] },
  { nombre: "Enlatados y Conservas", grupo: "Alimentación", subcategorias: ["Atún", "Sardinas", "Maíz dulce", "Vegetales mixtos"] },
  { nombre: "Condimentos y Azúcar", grupo: "Alimentación", subcategorias: ["Sal", "Azúcar", "Salsas tradicionales", "Especias"] },
  { nombre: "Cereales y Galletas", grupo: "Alimentación", subcategorias: ["Cereales de maíz", "Avena", "Galletas soda", "Galletas dulces"] },
  { nombre: "Limpieza del Hogar", grupo: "Limpieza", subcategorias: ["Detergente en polvo", "Detergente líquido", "Cloro", "Desinfectante", "Suavizante"] },
  { nombre: "Cuidado e Higiene Personal", grupo: "Higiene personal", subcategorias: ["Papel higiénico", "Pasta dental", "Jabón de baño", "Shampoo", "Desodorante"] },
  { nombre: "Mascotas", grupo: "Mascotas", subcategorias: ["Comida seca perros", "Comida seca gatos", "Arena para gatos"] },
];

export type ProductSeed = {
  nombre: string;
  slug: string;
  marca?: string;
  marcaOrigen?: string;
  categoria: string;
  subcategoria: string;
  presentacion: string;
  cantidad: number;
  unidad: string;
  unidadBase: string; // kg, l, und
  canasta: boolean;
  precioBase: number;
  codigo: string;
  descripcion?: string;
  imagen?: string;
  tiendas: { tienda: string; precio: number; promocion?: string }[];
};

export const productos: ProductSeed[] = [
  {
    nombre: "Arroz 99% Grano Entero",
    slug: "arroz-blanco-1-8-kg",
    marca: "Tío Pelón",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Arroz y Granos",
    subcategoria: "Arroz blanco",
    presentacion: "1.8 kg",
    cantidad: 1.8,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 1950,
    codigo: "7441001001021",
    descripcion: "Arroz blanco de grano entero 99%, libre de impurezas, cultivado y procesado en Guanacaste y el Pacífico Central.",
    imagen: "/img/products/arroz-blanco-1-8-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 2050 },
      { tienda: "MaxiPalí", precio: 2080 },
      { tienda: "Walmart Costa Rica", precio: 2150 },
      { tienda: "Megasuper", precio: 2220 },
      { tienda: "MasxMenos", precio: 2290 },
      { tienda: "Automercado", precio: 2450 },
    ],
  },
  {
    nombre: "Arroz Integral",
    slug: "arroz-integral-1-kg",
    marca: "Tío Pelón",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Arroz y Granos",
    subcategoria: "Arroz integral",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: false,
    precioBase: 1490,
    codigo: "7441001001090",
    descripcion: "Arroz integral con salvado intacto rico en fibra, minerales y vitaminas.",
    imagen: "/img/products/arroz-integral-1-kg.webp",
    tiendas: [
      { tienda: "Megasuper", precio: 1580 },
      { tienda: "Walmart Costa Rica", precio: 1620 },
      { tienda: "MasxMenos", precio: 1675 },
      { tienda: "Automercado", precio: 1750 },
    ],
  },
  {
    nombre: "Frijoles Negros",
    slug: "frijoles-negros-1-kg",
    marca: "Don Pedro",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Arroz y Granos",
    subcategoria: "Frijoles negros",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 1720,
    codigo: "7441002002034",
    descripcion: "Frijol negro seleccionado de cocción rápida y caldo espeso, estándar en la mesa costarricense.",
    imagen: "/img/products/frijoles-negros-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 1790 },
      { tienda: "MaxiPalí", precio: 1820 },
      { tienda: "MasxMenos", precio: 1890 },
      { tienda: "Walmart Costa Rica", precio: 1890 },
      { tienda: "Megasuper", precio: 1940 },
      { tienda: "Automercado", precio: 2050 },
    ],
  },
  {
    nombre: "Frijoles Rojos de Seda",
    slug: "frijoles-rojos-1-kg",
    marca: "Don Pedro",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Arroz y Granos",
    subcategoria: "Frijoles rojos",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 1750,
    codigo: "7441002002041",
    descripcion: "Frijol rojo de seda grano suave y brillante, ideal para chifrijo y olla de carne.",
    imagen: "/img/products/frijoles-rojos-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 1840 },
      { tienda: "MaxiPalí", precio: 1860 },
      { tienda: "MasxMenos", precio: 1920 },
      { tienda: "Walmart Costa Rica", precio: 1940 },
      { tienda: "Automercado", precio: 2100 },
    ],
  },
  {
    nombre: "Leche Entera",
    slug: "leche-entera-1-l",
    marca: "Dos Pinos",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Lácteos y Huevos",
    subcategoria: "Leche",
    presentacion: "1 L",
    cantidad: 1,
    unidad: "l",
    unidadBase: "l",
    canasta: true,
    precioBase: 1020,
    codigo: "7441003003011",
    descripcion: "Leche entera fluida ultrapasteurizada 100% de vacas de pastoreo de cooperativas costarricenses.",
    imagen: "/img/products/leche-entera-1-l.webp",
    tiendas: [
      { tienda: "Palí", precio: 1060 },
      { tienda: "MaxiPalí", precio: 1070 },
      { tienda: "MasxMenos", precio: 1095 },
      { tienda: "Walmart Costa Rica", precio: 1095 },
      { tienda: "Megasuper", precio: 1140 },
      { tienda: "Automercado", precio: 1250 },
    ],
  },
  {
    nombre: "Leche Semidescremada 2%",
    slug: "leche-semidescremada-1-l",
    marca: "Dos Pinos",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Lácteos y Huevos",
    subcategoria: "Leche",
    presentacion: "1 L",
    cantidad: 1,
    unidad: "l",
    unidadBase: "l",
    canasta: true,
    precioBase: 1030,
    codigo: "7441003003028",
    descripcion: "Leche semidescremada reducida en grasa al 2%, fortificada con vitamina A y D.",
    imagen: "/img/products/leche-semidescremada-1-l.webp",
    tiendas: [
      { tienda: "Palí", precio: 1070 },
      { tienda: "Walmart Costa Rica", precio: 1100 },
      { tienda: "MasxMenos", precio: 1100 },
      { tienda: "Megasuper", precio: 1150 },
      { tienda: "Automercado", precio: 1260 },
    ],
  },
  {
    nombre: "Huevos Grandes",
    slug: "huevos-30-unidades",
    marca: "Huevo Feliz",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Lácteos y Huevos",
    subcategoria: "Huevos",
    presentacion: "30 unidades",
    cantidad: 30,
    unidad: "und",
    unidadBase: "und",
    canasta: true,
    precioBase: 2650,
    codigo: "7441004004015",
    descripcion: "Cartón con 30 huevos grandes frescos de granjas avícolas de Alajuela y San Ramón.",
    imagen: "/img/products/huevos-30-unidades.webp",
    tiendas: [
      { tienda: "Palí", precio: 2790 },
      { tienda: "MaxiPalí", precio: 2850 },
      { tienda: "MasxMenos", precio: 2950 },
      { tienda: "Walmart Costa Rica", precio: 2990 },
      { tienda: "Megasuper", precio: 3050 },
      { tienda: "Automercado", precio: 3190 },
    ],
  },
  {
    nombre: "Huevos Medianos",
    slug: "huevos-12-unidades",
    marca: "Granja Azul",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Lácteos y Huevos",
    subcategoria: "Huevos",
    presentacion: "12 unidades",
    cantidad: 12,
    unidad: "und",
    unidadBase: "und",
    canasta: true,
    precioBase: 1350,
    codigo: "7441004004022",
    descripcion: "Empaque de 12 huevos frescos seleccionados.",
    imagen: "/img/products/huevos-12-unidades.webp",
    tiendas: [
      { tienda: "Palí", precio: 1390 },
      { tienda: "MasxMenos", precio: 1450 },
      { tienda: "Megasuper", precio: 1490 },
      { tienda: "Automercado", precio: 1590 },
    ],
  },
  {
    nombre: "Café Molido Gourmet",
    slug: "cafe-molido-340-g",
    marca: "Café Britt",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Café y Bebidas",
    subcategoria: "Café molido",
    presentacion: "340 g",
    cantidad: 340,
    unidad: "g",
    unidadBase: "kg",
    canasta: false,
    precioBase: 3850,
    codigo: "7441005005019",
    descripcion: "Café arábica de estricta altura (SHB), tueste oscuro con notas a chocolate y caramelo.",
    imagen: "/img/products/cafe-molido-340-g.webp",
    tiendas: [
      { tienda: "Walmart Costa Rica", precio: 3990 },
      { tienda: "Megasuper", precio: 4050 },
      { tienda: "MasxMenos", precio: 4090 },
      { tienda: "Automercado", precio: 4150 },
    ],
  },
  {
    nombre: "Café Clásico Molido",
    slug: "cafe-clasico-500-g",
    marca: "Café 1820",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Café y Bebidas",
    subcategoria: "Café molido",
    presentacion: "500 g",
    cantidad: 500,
    unidad: "g",
    unidadBase: "kg",
    canasta: true,
    precioBase: 3200,
    codigo: "7441005005026",
    descripcion: "El café emblemático de los hogares costarricenses, mezcla de alturas balanceada.",
    imagen: "/img/products/cafe-clasico-500-g.webp",
    tiendas: [
      { tienda: "Palí", precio: 3350 },
      { tienda: "MaxiPalí", precio: 3390 },
      { tienda: "Walmart Costa Rica", precio: 3450 },
      { tienda: "MasxMenos", precio: 3490 },
      { tienda: "Automercado", precio: 3650 },
    ],
  },
  {
    nombre: "Café Soluble Instantáneo",
    slug: "cafe-soluble-170-g",
    marca: "Nescafé Clásico",
    marcaOrigen: "Distribuido en Costa Rica",
    categoria: "Café y Bebidas",
    subcategoria: "Café soluble",
    presentacion: "170 g",
    cantidad: 170,
    unidad: "g",
    unidadBase: "kg",
    canasta: false,
    precioBase: 4600,
    codigo: "7613035123456",
    descripcion: "Café 100% puro soluble de preparación instantánea.",
    imagen: "/img/products/cafe-soluble-170-g.webp",
    tiendas: [
      { tienda: "MasxMenos", precio: 4890 },
      { tienda: "MaxiPalí", precio: 4990 },
      { tienda: "Automercado", precio: 5290 },
    ],
  },
  {
    nombre: "Pollo Entero Limpio",
    slug: "pollo-entero-1-kg",
    marca: "Pipasa",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Carnes y Pollo",
    subcategoria: "Pollo entero",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 2890,
    codigo: "7441006006013",
    descripcion: "Pollo entero fresco sin menudos, criado bajo estándares veterinarios de Costa Rica.",
    imagen: "/img/products/pollo-entero-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 3050 },
      { tienda: "MaxiPalí", precio: 3090 },
      { tienda: "MasxMenos", precio: 3190 },
      { tienda: "Walmart Costa Rica", precio: 3190 },
      { tienda: "Automercado", precio: 3450 },
    ],
  },
  {
    nombre: "Pechuga Deshuesada",
    slug: "pechuga-pollo-1-kg",
    marca: "Pipasa",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Carnes y Pollo",
    subcategoria: "Pechuga de pollo",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 3890,
    codigo: "7441006006020",
    descripcion: "Pechuga de pollo deshuesada y sin piel, lista para filetear.",
    imagen: "/img/products/pechuga-pollo-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 4050 },
      { tienda: "MasxMenos", precio: 4190 },
      { tienda: "Megasuper", precio: 4250 },
      { tienda: "Automercado", precio: 4490 },
    ],
  },
  {
    nombre: "Aceite de Girasol 100%",
    slug: "aceite-girasol-1-l",
    marca: "Clover",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Aceites y Grasas",
    subcategoria: "Aceite de girasol",
    presentacion: "1 L",
    cantidad: 1,
    unidad: "l",
    unidadBase: "l",
    canasta: true,
    precioBase: 2050,
    codigo: "7441007007017",
    descripcion: "Aceite vegetal 100% puro de girasol, rico en vitamina E.",
    imagen: "/img/products/aceite-girasol-1-l.webp",
    tiendas: [
      { tienda: "Palí", precio: 2180 },
      { tienda: "MasxMenos", precio: 2250 },
      { tienda: "MaxiPalí", precio: 2260 },
      { tienda: "Walmart Costa Rica", precio: 2280 },
      { tienda: "Automercado", precio: 2490 },
    ],
  },
  {
    nombre: "Aceite Vegetal",
    slug: "aceite-vegetal-900-ml",
    marca: "Capullo",
    marcaOrigen: "Distribuido en Costa Rica",
    categoria: "Aceites y Grasas",
    subcategoria: "Aceite vegetal",
    presentacion: "900 ml",
    cantidad: 900,
    unidad: "ml",
    unidadBase: "l",
    canasta: true,
    precioBase: 1820,
    codigo: "7441007007024",
    descripcion: "Aceite vegetal de uso diario sin colesterol.",
    imagen: "/img/products/aceite-vegetal-900-ml.webp",
    tiendas: [
      { tienda: "Palí", precio: 1890 },
      { tienda: "MasxMenos", precio: 1950 },
      { tienda: "Megasuper", precio: 1990 },
    ],
  },
  {
    nombre: "Atún Lomitos en Aceite",
    slug: "atun-enlatado-140-g",
    marca: "Pronto",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Enlatados y Conservas",
    subcategoria: "Atún",
    presentacion: "140 g",
    cantidad: 140,
    unidad: "g",
    unidadBase: "kg",
    canasta: true,
    precioBase: 920,
    codigo: "7441008008014",
    descripcion: "Lomitos de atún en aceite vegetal con trocitos de vegetales, fuente natural de Omega 3.",
    imagen: "/img/products/atun-enlatado-140-g.webp",
    tiendas: [
      { tienda: "Palí", precio: 990 },
      { tienda: "Walmart Costa Rica", precio: 1020 },
      { tienda: "MasxMenos", precio: 1050 },
      { tienda: "Megasuper", precio: 1080 },
    ],
  },
  {
    nombre: "Pasta Spaghetti",
    slug: "pasta-spaghetti-500-g",
    marca: "Pastas Roma",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Pastas y Harinas",
    subcategoria: "Spaghetti",
    presentacion: "500 g",
    cantidad: 500,
    unidad: "g",
    unidadBase: "kg",
    canasta: true,
    precioBase: 690,
    codigo: "7441009009011",
    descripcion: "Pasta elaborada con sémola de trigo durum, consistencia al dente.",
    imagen: "/img/products/pasta-spaghetti-500-g.webp",
    tiendas: [
      { tienda: "Palí", precio: 750 },
      { tienda: "Megasuper", precio: 780 },
      { tienda: "MasxMenos", precio: 790 },
      { tienda: "Automercado", precio: 840 },
    ],
  },
  {
    nombre: "Papel Higiénico Doble Hoja",
    slug: "papel-higienico-12-rollos",
    marca: "Scott RindeMás",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Cuidado e Higiene Personal",
    subcategoria: "Papel higiénico",
    presentacion: "12 rollos",
    cantidad: 12,
    unidad: "rol",
    unidadBase: "und",
    canasta: true,
    precioBase: 2600,
    codigo: "7501001112233",
    descripcion: "Papel higiénico doble hoja con tecnología de máxima absorción y suavidad.",
    imagen: "/img/products/papel-higienico-12-rollos.webp",
    tiendas: [
      { tienda: "PriceSmart Costa Rica", precio: 2690, promocion: "MEMBERSHIP" },
      { tienda: "MaxiPalí", precio: 2890 },
      { tienda: "MasxMenos", precio: 2990 },
      { tienda: "Walmart Costa Rica", precio: 2990 },
      { tienda: "Automercado", precio: 3290 },
    ],
  },
  {
    nombre: "Detergente en Polvo Doble Poder",
    slug: "detergente-polvo-1-2-kg",
    marca: "Ariel",
    marcaOrigen: "Distribuido en Costa Rica",
    categoria: "Limpieza del Hogar",
    subcategoria: "Detergente en polvo",
    presentacion: "1.2 kg",
    cantidad: 1.2,
    unidad: "kg",
    unidadBase: "kg",
    canasta: false,
    precioBase: 3290,
    codigo: "7501002223344",
    descripcion: "Detergente de lavado profundo para ropa blanca y de color.",
    imagen: "/img/products/detergente-polvo-1-2-kg.webp",
    tiendas: [
      { tienda: "MasxMenos", precio: 3450 },
      { tienda: "MaxiPalí", precio: 3490 },
      { tienda: "Megasuper", precio: 3550 },
      { tienda: "Automercado", precio: 3790 },
    ],
  },
  {
    nombre: "Queso Crema Tradicional",
    slug: "queso-crema-250-g",
    marca: "Dos Pinos",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Lácteos y Huevos",
    subcategoria: "Queso",
    presentacion: "250 g",
    cantidad: 250,
    unidad: "g",
    unidadBase: "kg",
    canasta: false,
    precioBase: 1820,
    codigo: "7441003003097",
    descripcion: "Queso crema pasteurizado de untar, suave y textura homogénea.",
    imagen: "/img/products/queso-crema-250-g.webp",
    tiendas: [
      { tienda: "Palí", precio: 1920 },
      { tienda: "MasxMenos", precio: 1990 },
      { tienda: "Megasuper", precio: 2050 },
      { tienda: "Automercado", precio: 2190 },
    ],
  },
  {
    nombre: "Banano Criollo Fresco",
    slug: "banano-1-kg",
    marca: "Fruta Fresca",
    marcaOrigen: "Cosechado en Costa Rica",
    categoria: "Frutas y Verduras",
    subcategoria: "Frutas frescas",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 570,
    codigo: "2000000000010",
    descripcion: "Banano fresco costarricense de calidad primera.",
    imagen: "/img/products/banano-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 610 },
      { tienda: "MasxMenos", precio: 640 },
      { tienda: "Automercado", precio: 750 },
    ],
  },
  {
    nombre: "Tomate de Mesa",
    slug: "tomate-1-kg",
    marca: "Verduras Frescas",
    marcaOrigen: "Cosechado en Costa Rica",
    categoria: "Frutas y Verduras",
    subcategoria: "Verduras frescas",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 1450,
    codigo: "2000000000027",
    descripcion: "Tomate de mesa firme y maduro, seleccionado para ensaladas y guisos.",
    imagen: "/img/products/tomate-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 1550 },
      { tienda: "MasxMenos", precio: 1650 },
      { tienda: "Automercado", precio: 1890 },
    ],
  },
  {
    nombre: "Sal Yodada de Mesa",
    slug: "sal-mesa-500-g",
    marca: "Sal Sol",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Condimentos y Azúcar",
    subcategoria: "Sal",
    presentacion: "500 g",
    cantidad: 500,
    unidad: "g",
    unidadBase: "kg",
    canasta: true,
    precioBase: 340,
    codigo: "7441010010014",
    descripcion: "Sal refinada con yodo y flúor según la legislación de salud de Costa Rica.",
    imagen: "/img/products/sal-mesa-500-g.webp",
    tiendas: [
      { tienda: "Palí", precio: 360 },
      { tienda: "MasxMenos", precio: 380 },
      { tienda: "Automercado", precio: 420 },
    ],
  },
  {
    nombre: "Azúcar Blanco Especial",
    slug: "azucar-1-kg",
    marca: "El Viejo",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Condimentos y Azúcar",
    subcategoria: "Azúcar",
    presentacion: "1 kg",
    cantidad: 1,
    unidad: "kg",
    unidadBase: "kg",
    canasta: true,
    precioBase: 910,
    codigo: "7441011011018",
    descripcion: "Azúcar blanco de caña producido en ingenios guanacastecos.",
    imagen: "/img/products/azucar-1-kg.webp",
    tiendas: [
      { tienda: "Palí", precio: 950 },
      { tienda: "MasxMenos", precio: 975 },
      { tienda: "Megasuper", precio: 990 },
      { tienda: "Automercado", precio: 1050 },
    ],
  },
  {
    nombre: "Salsa Condimento Lizano",
    slug: "salsa-lizano-700-ml",
    marca: "Lizano",
    marcaOrigen: "Fabricado en Costa Rica",
    categoria: "Condimentos y Azúcar",
    subcategoria: "Salsas tradicionales",
    presentacion: "700 ml",
    cantidad: 700,
    unidad: "ml",
    unidadBase: "l",
    canasta: true,
    precioBase: 2450,
    codigo: "7441012012015",
    descripcion: "La salsa vegetal tradicional indispensable para el gallo pinto y la gastronomía típica tica.",
    imagen: "/img/products/salsa-lizano-700-ml.webp",
    tiendas: [
      { tienda: "Palí", precio: 2550 },
      { tienda: "Walmart Costa Rica", precio: 2650 },
      { tienda: "MasxMenos", precio: 2690 },
      { tienda: "Automercado", precio: 2850 },
    ],
  },
  {
    nombre: "Pasta Dental Triple Acción",
    slug: "pasta-dental-125-g",
    marca: "Colgate",
    marcaOrigen: "Distribuido en Costa Rica",
    categoria: "Cuidado e Higiene Personal",
    subcategoria: "Pasta dental",
    presentacion: "125 g",
    cantidad: 125,
    unidad: "g",
    unidadBase: "kg",
    canasta: false,
    precioBase: 1250,
    codigo: "7501003334455",
    descripcion: "Protección anticaries, blancura y aliento fresco.",
    imagen: "/img/products/pasta-dental-125-g.webp",
    tiendas: [
      { tienda: "Palí", precio: 1290 },
      { tienda: "MasxMenos", precio: 1350 },
      { tienda: "Megasuper", precio: 1390 },
      { tienda: "Automercado", precio: 1490 },
    ],
  },
  {
    nombre: "Cereal Corn Flakes",
    slug: "cereal-caja-430-g",
    marca: "Kellogg's",
    marcaOrigen: "Distribuido en Costa Rica",
    categoria: "Cereales y Galletas",
    subcategoria: "Cereales de maíz",
    presentacion: "430 g",
    cantidad: 430,
    unidad: "g",
    unidadBase: "kg",
    canasta: false,
    precioBase: 2390,
    codigo: "7501004445566",
    descripcion: "Hojuelas de maíz tostadas enriquecidas con vitaminas del complejo B y hierro.",
    imagen: "/img/products/cereal-caja-430-g.webp",
    tiendas: [
      { tienda: "MasxMenos", precio: 2590 },
      { tienda: "Walmart Costa Rica", precio: 2590 },
      { tienda: "Automercado", precio: 2690 },
    ],
  },
  {
    nombre: "Alimento Completo Adultos",
    slug: "comida-perros-3-kg",
    marca: "Pedigree",
    marcaOrigen: "Distribuido en Costa Rica",
    categoria: "Mascotas",
    subcategoria: "Comida seca perros",
    presentacion: "3 kg",
    cantidad: 3,
    unidad: "kg",
    unidadBase: "kg",
    canasta: false,
    precioBase: 14200,
    codigo: "7501005556677",
    descripcion: "Nutrición completa para perros adultos de razas medianas y grandes.",
    imagen: "/img/products/comida-perros-3-kg.webp",
    tiendas: [
      { tienda: "PriceSmart Costa Rica", precio: 14800, promocion: "MEMBERSHIP" },
      { tienda: "Megasuper", precio: 15200 },
      { tienda: "Automercado", precio: 15900 },
    ],
  }
];
